name: Test Homebrew Tap

on: [push]

jobs:
  install_homebrew:
    runs-on: macos-latest
    steps:
      - name: Install Homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Tap Repo
        run: brew tap mtslzr/marmaduke-chromium
      - name: Update Brew
        run: brew update
      - name: Install Casks
        run: brew cask install marmaduke-chromium{,-nosync,-ungoogled}
